/* Akustiker John – interactions */
(function () {
  "use strict";

  /* Mobile nav */
  var toggle = document.querySelector(".nav-toggle");
  var nav = document.querySelector(".nav");
  if (toggle && nav) {
    toggle.addEventListener("click", function () {
      nav.classList.toggle("open");
      toggle.setAttribute("aria-expanded", nav.classList.contains("open"));
    });
    nav.addEventListener("click", function (e) {
      if (e.target.closest("a")) nav.classList.remove("open");
    });
  }

  /* Reveal on scroll */
  var reveals = document.querySelectorAll(".reveal");
  if ("IntersectionObserver" in window && reveals.length) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) { en.target.classList.add("in"); io.unobserve(en.target); }
      });
    }, { threshold: 0.12 });
    reveals.forEach(function (el, i) {
      el.style.transitionDelay = (i % 3) * 80 + "ms";
      io.observe(el);
    });
  } else {
    reveals.forEach(function (el) { el.classList.add("in"); });
  }

  /* FAQ accordion */
  document.querySelectorAll(".faq-q").forEach(function (q) {
    q.addEventListener("click", function () {
      q.parentElement.classList.toggle("open");
    });
  });

  /* Active nav highlight by path */
  var path = location.pathname.replace(/\/$/, "").split("/").pop() || "index";
  document.querySelectorAll(".nav a.navlink").forEach(function (a) {
    var href = (a.getAttribute("href") || "").replace(/\/$/, "").split("/").pop().replace(".html", "");
    if (href && (href === path || href === path.replace(".html", ""))) a.classList.add("active");
  });

  /* -------- YouTube feed loader ----------
     Reads videos.json (generated by the scheduled GitHub Action).
     Fills any [data-yt-feed] container with up to data-count cards. */
  // Bevorzugt das lokal gespiegelte Vorschaubild (DSGVO – kein Google-Request).
  function ytThumb(v) { return v.thumb || ("https://i.ytimg.com/vi/" + v.id + "/hqdefault.jpg"); }
  function fmtDate(iso) {
    try {
      return new Date(iso).toLocaleDateString("de-DE", { day: "numeric", month: "long", year: "numeric" });
    } catch (e) { return ""; }
  }
  var feeds = document.querySelectorAll("[data-yt-feed]");
  if (feeds.length) {
    fetch("videos.json", { cache: "no-cache" })
      .then(function (r) { return r.ok ? r.json() : Promise.reject(); })
      .then(function (data) {
        var vids = (data && data.videos) || [];
        feeds.forEach(function (feed) {
          var count = parseInt(feed.getAttribute("data-count") || "6", 10);
          var slice = vids.slice(0, count);
          if (!slice.length) return;
          feed.innerHTML = slice.map(function (v) {
            return (
              '<a class="video-card" href="https://www.youtube.com/watch?v=' + v.id +
              '" target="_blank" rel="noopener">' +
                '<div class="video-thumb"><img loading="lazy" src="' + ytThumb(v) +
                  '" alt="' + (v.title || "").replace(/"/g, "&quot;") + '">' +
                  '<div class="play"><span><svg width="22" height="22" viewBox="0 0 24 24" fill="#fff"><path d="M8 5v14l11-7z"/></svg></span></div>' +
                '</div>' +
                '<div class="video-meta"><h3>' + (v.title || "") + '</h3>' +
                (v.published ? '<time datetime="' + v.published + '">' + fmtDate(v.published) + "</time>" : "") +
                '</div>' +
              "</a>"
            );
          }).join("");
        });
      })
      .catch(function () { /* keep static fallback markup already in the page */ });
  }
})();
